# Generated by Django 5.2.4 on 2025-09-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0002_alter_predio_gerente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predio",
            name="nr_casas",
        ),
    ]
