# Generated by Django 5.2.4 on 2025-09-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gerente", "0004_contratos_casa"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagamentoRenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes_referencia", models.DateField(verbose_name="Mês de Referência")),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entidade", models.CharField(default="9501", max_length=4)),
                (
                    "referencia",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Referência"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pago", "Pago"), ("nao_pago", "Não Pago")],
                        default="nao_pago",
                        max_length=10,
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamentos",
                        to="gerente.contratos",
                    ),
                ),
            ],
            options={
                "unique_together": {("contrato", "mes_referencia")},
            },
        ),
    ]
