# Generated by Django 5.2.4 on 2025-09-11 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrador", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquilino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contacto", models.CharField(max_length=15, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contratos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("valor_renda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracao_meses", models.IntegerField(verbose_name="Duração (meses)")),
                (
                    "inquilino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos",
                        to="gerente.inquilino",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Casa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                (
                    "predio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casas",
                        to="administrador.predio",
                    ),
                ),
                (
                    "inquilino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="casas_alugadas",
                        to="gerente.inquilino",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("eletrico", "Elétrico"),
                            ("hidraulico", "Hidráulico"),
                            ("estrutural", "Estrutural"),
                            ("geral", "Geral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_progresso", "Em Progresso"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                (
                    "casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="gerente.casa",
                    ),
                ),
                (
                    "solicitado_por_gerente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_solicitadas_gerente",
                        to="administrador.gerente",
                    ),
                ),
                (
                    "solicitado_por_inquilino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_solicitadas_inquilino",
                        to="gerente.inquilino",
                    ),
                ),
            ],
        ),
    ]
