# Generated by Django 5.2.4 on 2025-09-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manutencao",
            name="casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes",
                to="gerente.casa",
            ),
        ),
    ]
