# Generated by Django 5.2.4 on 2025-09-12 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0003_remove_predio_nr_casas"),
        ("gerente", "0002_alter_manutencao_casa"),
    ]

    operations = [
        migrations.AddField(
            model_name="manutencao",
            name="predio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manutencoes_gerais",
                to="administrador.predio",
            ),
        ),
    ]
