# Generated by Django 5.2.4 on 2025-09-13 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerente", "0003_manutencao_predio"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratos",
            name="casa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contratos",
                to="gerente.casa",
            ),
        ),
    ]
