# Generated by Django 5.2.4 on 2025-09-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0003_remove_predio_nr_casas"),
        ("gerente", "0004_contratos_casa"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquilino",
            name="gerente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inquilinos_registrados",
                to="administrador.gerente",
            ),
        ),
    ]
